name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 0
    - name: install libudev-dev eigen
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libeigen3-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=artifacts .
    - name: make
      run: make VERBOSE=1 -j2
    - name: make install
      run: make install
    - name: Archive production artifacts2
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts